# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14dc64df1baa38f25b17d975ed529f6b70c705118d746ee019caf41d9b9cc9361a1baa6e67a1f2a91f5eb62832de37b34b9e66900fe5889616a6edb190cb1e0c

test:
  secret_key_base: dea980e024768100c76c4d07e5bcb6eb55b296020329aed5f608e09f90a5bb9fe93cbbec2a8cf8e15e826a111e1d29e9a25360be795ac9b4db221df349558808

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
